### PR TITLE
Implement barcode scanning

### PR DESCRIPTION
**Pull request by keithtweed**
Solves #20 

This adds
- Scanning a barcode from the camera to fill in either the serial number or description field

### CODE REVIEW

**Comment by keithtweed** [comment]
Merge conflicts have been resolved and tested

**Review by nortif8 — CHANGES_REQUESTED** [review]
Two things I am unsure of/need changes:
1. It appears that this tries to scan serial numbers using barcode logic (outside of the scope of #20 anyways)
2. The description based on the barcode should not be the raw value of the barcode

**Comment by nortif8** [comment]
For 1: I wasn't aware of that. We could possibly have both barcode scanning and text recognition as options during the serial number scanning.
We can keep the current behavior in this PR of it setting the serial number as well, though it should probably not override a currently set serial number.
For 2: Sounds good

**Review by nortif8 — CHANGES_REQUESTED** [review]
Seems to function properly, could have better errors on non-upc input (though in my opinion is not worth blocking the PR)

**Pull request merged**
