### PR TITLE
Adds Item Class

### PR DESCRIPTION
**Pull request by nortif8**
Adds an Item Class with Javadocs, getters, setters and constructors.
Part of fulfilling #1

### CODE REVIEW

**Comment by maodus** [comment]
Looks good. This can be merged now or drafted until Photographs and Tags are implemented fully. Thoughts?

**Comment by nortif8** [comment]
@maodus I'll change it to a draft let's wait for images to be added and I've added tags to the item class.

**Comment by nortif8** [comment]
I added a list of `Image` (not yet fully implemented) to `Item`.
I think that using a builder pattern instead of these constructors would be good, as they are quite big.
If we want a builder pattern, I can add that to this PR or do it in another one. Just let me know

**Comment by nortif8** [comment]
Created a PR to add a builder class (#42). If we want that in this PR we can simply rebase that PR.

**Comment by nortif8** [comment]
superseded by #45

**Pull request closed without merging**
